version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=lambda,s3,stepfunctions
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4566:4566"
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  stepfunctions:
    container_name: stepfunctions
    image: amazon/aws-stepfunctions-local:latest
    environment:
      - LAMBDA_ENDPOINT=http://localstack:4566
      - STEPFUNCTIONS_LAMBDA_ENDPOINT=http://host.docker.internal:4566 ##追記
    ports:
      - '8083:8083'
